steps:
  -
    name: "Build :cloudformation: templates"
    command: "make clean build"
    artifact_paths: "build/*"
    agents:
      queue: aws-stack
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: build

  - wait

  -
    name: "Upload :cloudformation: templates"
    command: ".buildkite/upload.sh"
    agents:
      queue: aws-stack