---
AWSTemplateFormatVersion: '2010-09-09'
Description: Publish Buildkite Metrics to Cloudwatch

Parameters:
  BuildkiteApiAccessToken:
    Description: Your Buildkite personal api access token
    Type: String
    NoEcho: true

  BuildkiteOrgSlug:
    Description: Your Buildkite organization slug
    Type: String

  QueueName:
    Description: An optional queuename to filter published metrics to
    Type: String
    Default: ""

  PollRate:
    Description: How often to update metrics
    Type: String
    Default: "1 minute"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaExecutionPolicy:
    DependsOn: LambdaExecutionRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AccessToCloudwatchForBuildkiteMetrics
      Roles:
      - $(LambdaExecutionRole)
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudwatch:PutMetricData
          - autoscaling:SetInstanceHealth
          Resource:
          - "*"

  BuildkiteMetricsFunction:
    Type: AWS::Lambda::Function
    DependsOn:
    - LambdaExecutionRole
    - LambdaExecutionPolicy
    Properties:
      Code:
        S3Bucket: buildkite-metrics
        S3Key: buildkite-metrics-v1.2.0-29-gc4d48c4-lambda.zip
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Timeout: 60
      Handler: handler.handle
      Runtime: python2.7
      MemorySize: 128
      Environment:
        Variables:
          BUILDKITE_TOKEN: $(BuildkiteApiAccessToken)
          BUILDKITE_ORG: $(BuildkiteOrgSlug)
          BUILDKITE_QUEUE: $(QueueName)

  ScheduledRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: !Join [ "", [ "rate(", $(PollRate), ")" ] ]
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "BuildkiteMetricsFunction"
              - "Arn"
          Id: "TargetBuildkiteMetricsFunction"

  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: $(BuildkiteMetricsFunction)
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"