
Parameters:
  BuildkiteApiAccessToken:
    Description: Your Buildkite personal api access token
    Type: String
    NoEcho: true

  BuildkiteOrgSlug:
    Description: Your Buildkite organization slug
    Type: String

  KeyName:
    Description: The ssh keypair used for the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: default

  BinUrl:
    Description: The url to download the binary from
    Type: String
    Default: http://s3.amazonaws.com://buildkite-cloudwatch-metrics-publisher/master/buildkite-cloudwatch-metrics

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - autoscaling:SetInstanceHealth
                Resource: "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ $(IAMRole) ]

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: $(LaunchConfiguration)
      AvailabilityZones: !GetAZs
      MinSize: 1
      MaxSize: 1
      Tags:
        - Key: Role
          Value: buildkite-metrics
          PropagateAtLaunch: true

    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPC/EC2 Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceMonitoring: true
      SecurityGroups: [ $(SecurityGroup) ]
      ImageId: ami-8fcee4e5
      InstanceType: t2.nano
      IamInstanceProfile: $(InstanceProfile)
      KeyName: $(KeyName)
      UserData: !Base64 |
        #!/bin/bash -x
        export AWS_REGION=$(AWS::Region)
        export INSTANCE=\$(curl http://169.254.169.254/latest/meta-data/instance-id)
        curl -Lf $(BinUrl) -o /usr/bin/buildkite-cloudwatch-metrics \
          && chmod +x /usr/bin/buildkite-cloudwatch-metrics
        /opt/aws/bin/cfn-signal -e \$? \
            --stack $(AWS::StackName) --resource 'AutoScalingGroup' --region $(AWS::Region)
        /usr/bin/buildkite-cloudwatch-metrics -org "$(BuildkiteOrgSlug)" -token "$(BuildkiteApiAccessToken)" -interval 30s
        aws autoscaling set-instance-health --instance-id \$INSTANCE --health-status Unhealthy
