
Parameters:
  BuildkiteApiAccessToken:
    Description: Your Buildkite personal api access token
    Type: String
    NoEcho: true

  BuildkiteOrgSlug:
    Description: Your Buildkite organization slug
    Type: String

  KeyName:
    Description: The ssh keypair used for the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: default

  BinUrl:
    Description: The url to download the binary from
    Type: String
    Default: https://s3.amazonaws.com/buildkite-metrics/buildkite-metrics-Linux-x86_64-v1.0.0-5-ge73a533

  QueueName:
    Description: An optional queuename to filter published metrics to
    Type: String
    Default: ""

  PollInterval:
    Description: How often to update metrics
    Type: String
    Default: "30s"



Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - autoscaling:SetInstanceHealth
                Resource: "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ $(IAMRole) ]

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: $(LaunchConfiguration)
      AvailabilityZones: !GetAZs
      MinSize: 1
      MaxSize: 1
      Tags:
        - Key: Role
          Value: buildkite-metrics
          PropagateAtLaunch: true

    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPC/EC2 Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceMonitoring: true
      SecurityGroups: [ $(SecurityGroup) ]
      ImageId: ami-8fcee4e5
      InstanceType: t2.nano
      IamInstanceProfile: $(InstanceProfile)
      KeyName: $(KeyName)
      UserData: !Base64 |
        #!/bin/bash -xv
        /opt/aws/bin/cfn-init -s $(AWS::StackId) -r LaunchConfiguration --region $(AWS::Region)
        /opt/aws/bin/cfn-signal -e \$? -r 'cfn-init finished' \
          --stack $(AWS::StackName) --resource 'AutoScalingGroup' --region $(AWS::Region)

    Metadata:
      # see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
      AWS::CloudFormation::Init:
        config:
          files:
            "/usr/bin/buildkite-cloudwatch-metrics":
              mode: "000755"
              owner: root
              group: root
              source: $(BinUrl)
            "/etc/init/buildkite-cloudwatch-metrics.conf":
              mode: "000644"
              owner: root
              group: root
              content: |
                start on startup
                respawn
                env AWS_REGION=$(AWS::Region)
                script
                    mkfifo /tmp/buildkite-cloudwatch-metrics-log-fifo
                    ( logger -t buildkite-cloudwatch-metrics </tmp/buildkite-cloudwatch-metrics-log-fifo & )
                    exec >/tmp/buildkite-cloudwatch-metrics-log-fifo
                    exec 2>&1
                    rm /tmp/buildkite-cloudwatch-metrics-log-fifo
                    exec /usr/bin/buildkite-cloudwatch-metrics \
                        -org "$(BuildkiteOrgSlug)" -token "$(BuildkiteApiAccessToken)" \
                        -interval $(PollInterval) \
                        -queue "$(QueueName)"
                end script

          commands:
            01-start-buildkite-cloudwatch-metrics:
              command: start buildkite-cloudwatch-metrics
